server:
  port: 8090
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: gateway-service

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: proveedor-service
          uri: lb://proveedor-service
          predicates:
            - Path=/proveedor/**
        - id: acopio-service
          uri: lb://acopio-service
          predicates:
            - Path=/acopio/**
        - id: planilla-service
          uri: lb://planilla-service
          predicates:
            - Path=/planilla/**